services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - feast
      - mlflow
    env_file:
      - .env
    volumes:
      - ./services/feast/repo:/repo
      - ./core:/app/core
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d   # Monter les scripts pour initialiser la schéma - L'image officielle PostgreSQL possède un script de démarrage qui exécute automatiquement tous les fichiers présents dans ce dossier uniquement lors de la première création de la base de données.
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  prefect-server:
    build: 
      context: ./services/prefect
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_started
    env_file:
      - .env
    environment:
      - PREFECT_SERVER_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_LOGGING_LEVEL=INFO
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4200/api/health')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - ./services/prefect:/opt/prefect/flows
      - ./core:/opt/prefect/flows/core # monter les scripts du bd
      - ./data:/data    # Rendre les CSV accessibles au conteneur Prefect
      - ./services/feast/repo:/repo   # Accès à Feast
      - ./reports:/reports   
  feast:
    build: 
      context:  ./services/feast
      dockerfile: Dockerfile
    depends_on:
      - db
      - prefect-server
    environment:
      FEAST_USAGE: "FALSE"
    volumes:
      - ./services/feast/repo:/repo
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    command: mlflow server --backend-store-uri sqlite:///mlartifacts/mlflow.db --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --port 5000 --serve-artifacts --artifacts-destination /mlartifacts/artifacts
    volumes:
      - ./mlartifacts:/mlartifacts
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus:latest
    container_name: mlops-prometheus
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - api
  grafana:
    image: grafana/grafana:latest
    container_name: mlops-grafana
    volumes:
      - ./services/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  pgdata:
  mlartifacts:
  grafana-data: